packages/projects-docs/pages/learn/editor/interactive-readme.md
packages/projects-docs/pages/learn/getting-started/collaborate-share.md
packages/projects-docs/pages/learn/teams/permissions.md
packages/projects-docs/pages/tutorial/cli-tool.md
packages/projects-docs/pages/tutorial/install-system-packages.md

Update some links

---

packages/projects-docs/next.config.js

Add docker redirect

---

packages/projects-docs/pages/learn/setting-up/env.md

Add example Nix configuration

---

packages/projects-docs/pages/learn/setting-up/tasks.md
pnpm-lock.yaml

add documentation for the new `restartOn`

feat: add documentation for restartOn

---

.codesandbox/tasks.json
.github/workflows/csb.yml

<details>
<summary><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.light.svg#gh-dark-mode-only" /><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.svg#gh-light-mode-only" />&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/codesandbox/docs/draft/wizardly-sid?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=codesandbox&repo=docs&branch=draft/wizardly-sid">VS Code</a></summary>
<ul><li><a href="https://codesandbox.io/p/devtool/preview/tq3qsy?task=dev:projects&port=3001">Dev Projects</a></li><li><a …

Add Previews

---

packages/ios-docs/pages/meta.json
packages/ios-docs/pages/shortcuts.md
pnpm-lock.yaml

<details>
<summary><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.light.svg#gh-dark-mode-only" /><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.svg#gh-light-mode-only" />&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/codesandbox/docs/feature/ios-keybindings?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=codesandbox&repo=docs&branch=feature/ios-keybindings">VS Code</a></summary>
<ul><li><a href="https://codesandbox.io/p/devtool/preview/6trsk5?task=dev:projects&port=3001">Dev Projects</a></li><li><a …

CSB-5268 CodeSandbox for iOS keyboard shortcuts section

---

packages/projects-docs/pages/learn/setting-up/env.md

Some users asked for this, adding it to the docs :)

chore: add category about persistence of VMs

---

package.json
pnpm-lock.yaml
shared-components/Tabs.js
shared-components/Tabs.module.css

https://user-images.githubusercontent.com/1891339/193332449-396075a6-8a26-443b-a803-8212eb43905c.mp4
To use:
```
import { Tabs, WrapContent } from '../../../../../shared-components/Tabs'
<Tabs tabs={["Web", "VS Code", "iOS"]}>
<WrapContent>
content tab 1
</WrapContent>
<WrapContent>
content tab 2
</WrapContent>
<WrapContent>
content tab 3
</WrapContent>
</Tabs>
```

Tab Component

---

packages/codesandbox-theme-docs/src/misc/theme.tsx

SORRY! Prettier ran when I opened this file in CodeSandbox. I will highlight the actual change in a comment. Please make sure to double check if this works by doing the following:
1. Add a `BASE_PATH` environment variable, e.g. `BASE_PATH="/test"`
2. Make sure the docs run on the `/test` base path. No `/test` should result in 404.
3. Make sure the links in the docs have `/test` in them.
I did this in the ~Project~ Repository with:
```
BASE_PATH="/test"
```
So you can check that out too.

Prettier ran and deconstruct href from A

---

packages/projects-docs/pages/learn/integrations/github-app.mdx

Fix link to preview

---

packages/codesandbox-theme-docs/src/styles-cbs.css
shared-components/Tabs.js

Add the active tab to URL:
https://54wd7m-3000.preview.csb.app/learn/getting-started/collaborate-share?tab=repositories
https://54wd7m-3000.preview.csb.app/learn/getting-started/collaborate-share?tab=repositories#working-on-other-ides

feat: Tab router

---

packages/projects-docs/pages/learn/integrations/tailscale.mdx

By recommendation of our friends at Tailscale.

Use TS_AUTHKEY as environment variable name

---

packages/projects-docs/pages/learn/environment/vm.mdx

Updates free Ram to match requirements here
https://linear.app/codesandbox/issue/XTD-708/change-free-vm-spec

Reduce Free Ram to 2

---

packages/projects-docs/pages/learn/getting-started/_meta.json
packages/projects-docs/pages/learn/getting-started/setting-up-ios.mdx
packages/projects-docs/pages/learn/getting-started/setting-up-vscode.mdx
packages/projects-docs/pages/learn/repositories/editors.mdx

This PR reviews the copy of some newly updated Docs pages, both for iOS and VS Code.
It also adds some contextual links that may be useful for users navigating the Docs.

docs(iOS + VS Code): review updated docs

---

packages/projects-docs/pages/faq.mdx

Updating Database support section in CSB

Update Database faq to show docker support 

---

packages/projects-docs/theme.config.js

Now points to the right location

fix: link to edit this page on CodeSandbox

---

packages/projects-docs/pages/learn/environment/vm.mdx
packages/projects-docs/pages/learn/sandboxes/configuration.mdx

Much more clear docs for configuration of VMs. Also removing deprecated configuration methods.

docs(environment): update instructions for configuring environment using Dockerfile

---

packages/projects-docs/pages/learn/sandboxes/embedding.mdx

Very simple PR with a grammar review.

docs(learn/embeds): update some typos and clarify language

---

packages/projects-docs/pages/tutorial/convert-browser-sandbox-cloud.mdx

refactor(docs): vim mode and dependency picker

---

packages/projects-docs/pages/learn/environment/vm.mdx

Increase vCPUs to 32, memory to 64GB and storage to 256GB

feat: Upgrade VM specs

---

.devcontainer/Dockerfile

Update pnpm version from 7.4.0 to 8.7.4 in Dockerfile

fix: Update pnpm version

---

packages/projects-docs/pages/learn/environment/vm.mdx

Added a new section explaining the use of memory snapshotting in environments.

feat(Environment): Add section about memory snapshotting

---

packages/projects-docs/pages/learn/repositories/preview.mdx

Added instructions for configuring the service worker proxy

feat: docs on configuring the service worker proxy

---

packages/projects-docs/pages/learn/environment/devcontainers.mdx

Added example links to devcontainers.mdx file.

feat: add example links

---

packages/projects-docs/pages/learn/editors/overview.mdx
packages/projects-docs/pages/learn/index.mdx

Updated URLs for the 'Learn more' links in the 'learn/index' page.

refactor: Changed learn link URLs

---

packages/projects-docs/pages/faq.mdx

Adding item to FAQs to ensure users are aware of how to best experience CodeSandbox

feat: Add FAQ about support for operating systems and devices

---

packages/projects-docs/pages/learn/devboxes/synced-templates.mdx

Fix devbox synced templates docs

fix: Updated synced template URLs

---

packages/projects-docs/next.config.js
packages/projects-docs/pages/learn/devboxes/embedding.mdx
packages/projects-docs/pages/learn/sandboxes/_meta.json
packages/projects-docs/pages/learn/sandboxes/embedding.mdx

* removes unnecessary redirect
* add sandbox embeds with the react example
* change wording to legacy sandboxes

feat: Update devbox embedding description + add sandboxes

---

packages/projects-docs/next.config.js

Added redirection from '/learn/browser-sandboxes/configuration' to '/learn/legacy-sandboxes/configuration'

feat: Add redirect for an external community link

---

packages/projects-docs/pages/learn/plans/_meta.json
packages/projects-docs/pages/learn/plans/ubb.mdx

There is still a lot of content to add, but I think this will answer some of the biggest questions.
wdyt?

usage-based billing docs

---

packages/projects-docs/pages/faq.mdx
packages/projects-docs/pages/learn/editors/ios/overview.mdx
packages/projects-docs/pages/learn/editors/ios/setting-up-ios.mdx
packages/projects-docs/pages/learn/editors/ios/shortcuts.mdx
packages/projects-docs/pages/learn/editors/overview.mdx
packages/projects-docs/pages/learn/index.mdx
packages/projects-docs/pages/learn/repositories/overview.mdx

- Add banner to all mentions of the iOS app
- Add FAQ item

feat: Add information about support for CodeSandbox for iOS

---

packages/projects-docs/next.config.js
packages/projects-docs/pages/learn/plans/_meta.json
packages/projects-docs/pages/learn/plans/subscriptions.mdx

Add redirects for changes to UBB content, update title and remove unused code from plans.mdx
Closes PC-1682

fix: redirects 

---

packages/projects-docs/next.config.js

Add redirect from /learn/plans/ubb#credit to /learn/credit-usage/credits

fix: another redirect

---

packages/projects-docs/package.json
packages/projects-docs/pages/_app.js
packages/projects-docs/utils/cookieConsentConfig.js
packages/projects-docs/utils/cookieConsentTheme.css
packages/projects-docs/utils/useInitAnalytics.js
pnpm-lock.yaml

Similar to https://github.com/codesandbox/codesandbox-site/pull/404

feat: add cookie consent

---

packages/projects-docs/pages/learn/plans/pricing-faq.mdx

Preview [here](https://sm7yxr-3000.csb.app/learn/plans/pricing-faq#can-i-keep-my-legacy-per-user-pro-plan).

chore: update UBB deadline details

---

packages/projects-docs/next.config.js

adds redirect

---

packages/projects-docs/pages/faq.mdx
packages/projects-docs/pages/learn/plans/pricing-faq.mdx

Preview [here](https://nc93vh-3000.csb.app/faq). Closes PC-1953.

chore: add Account Management FAQs

---

packages/projects-docs/pages/learn/devboxes/synced-templates.mdx
packages/projects-docs/pages/learn/sandboxes/_meta.json

Preview [here](https://nvrdmg-3000.csb.app/learn/devboxes/synced-templates).

chore: add synced templates under Sandboxes and update its content

---

packages/projects-docs/pages/faq.mdx

This one comes up from time to time in Support. I wrote this FAQ based on a Slack message from Ives back in April.

chore: add domain whitelisting instructions to FAQ

---

packages/projects-docs/pages/faq.mdx
packages/projects-docs/pages/learn/browser-sandboxes/_meta.json
packages/projects-docs/pages/learn/browser-sandboxes/cli-api.mdx
packages/projects-docs/pages/learn/browser-sandboxes/overview.mdx
packages/projects-docs/pages/learn/legacy-sandboxes/test.mdx
packages/projects-docs/pages/learn/vm-sandboxes/your-first-sandbox.mdx
packages/projects-docs/pages/tutorial/convert-browser-sandbox-cloud.mdx

updating various links to reflect new VM Sandbox/Browser Sandbox sections
Renaming Browser Sandboxes Editor Features to Overview for consistency with VM/Legacy Sandbox sections

updating links and structures for consistency and accuracy

---

packages/projects-docs/pages/sdk/_meta.json
packages/projects-docs/pages/sdk/cli.mdx
packages/projects-docs/pages/sdk/create-resume.mdx
packages/projects-docs/pages/sdk/host-privacy.mdx
packages/projects-docs/pages/sdk/tracing.mdx

Perfect! Let me provide a summary of all the documentation changes I've made:
I have successfully updated the CodeSandbox SDK documentation to reflect all the new features from the recent release. Here's a comprehensive overview of what was accomplished:
1. **`packages/projects-docs/pages/sdk/create-resume.mdx`**
- Added documentation for the new `get()` method for efficient single sandbox retrieval
- Added documentation for the new `listRunning()` method to monitor running VMs
- Updated privacy options documentation to include the new `public-hosts` privacy level
2. **`packages/projects-docs/pages/sdk/host-privacy.mdx`**
- Completely restructured to explain all privacy levels clearly
- Added detailed explanation of the new `public-hosts` privacy option
- Updated examples to demonstrate …

docs: update SDK documentation for v2.1 release features
