codesandbox/docs

packages/sandbox-docs/next.config.js
I found some links that actually are pointing to `docs/start`. Let's add a not permanent redirect to it.
=> Add start to overview redirect to sandbox docs

packages/sandbox-docs/next.config.js
=> Fix broken api link with a redirection to /api-reference

packages/projects-docs/pages/learn/setting-up/secrets.md
=> Fix spelling mistake

packages/projects-docs/pages/learn/editor/shortcuts.md
When the shortcut has been updated in projects we need to update the docs page.
=> Update open git panel shortcut

packages/sandbox-docs/pages/faq.md
In practice, we don't increase this limit.
Resolves SPT-155.
=> Remove Offer to Increase Upload Limit

packages/projects-docs/pages/learn/integrations/github-app.md
Added link to the GitHub App Page in the Docs - https://github.com/apps/codesandbox
=> Add reference to GitHub App Page

.codesandbox/tasks.json
<details>
<summary><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.light.svg#gh-dark-mode-only" /><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.svg#gh-light-mode-only" />&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/codesandbox/docs/draft/silly-cookies?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=codesandbox&repo=docs&branch=draft/silly-cookies">VS Code</a></summary>
<ul><li><a href="https://codesandbox.io/p/devtool/preview/cd5szq?task=dev:projects&port=3001">Dev Projects</a></li><li><a …
=> chore: enable preview link for vscode docs

packages/sandbox-docs/pages/ci.md
<details>
<summary><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.light.svg#gh-dark-mode-only" /><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.svg#gh-light-mode-only" />&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/codesandbox/docs/draft/pensive-ishizaka?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=codesandbox&repo=docs&branch=draft/pensive-ishizaka">VS Code</a></summary>
<ul><li><a href="https://codesandbox.io/p/devtool/preview/8vhj0b?task=dev:projects&port=3001">Dev Projects</a></li><li><a …
=> chore: add a note for CodeSandbox CI for private repos

packages/projects-docs/pages/learn/integrations/github-app.md
This PR adds information about our new Deployments integration to the GitHub App docs. It also does some minor copy editing throughout the page.
=> Update GitHub App docs

packages/projects-docs/pages/tutorial/getting-started-with-docker.md
<details>
<summary><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.light.svg#gh-dark-mode-only" /><img alt="CodeSandbox logo" src="https://raw.githubusercontent.com/codesandbox/open-in-codesandbox/main/assets/csb.svg#gh-light-mode-only" />&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/codesandbox/docs/draft/fragrant-surf?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=codesandbox&repo=docs&branch=draft/fragrant-surf">VS Code</a></summary>
<ul><li><a href="https://codesandbox.io/p/devtool/preview/0usopt?task=dev:projects&port=3001">Dev Projects</a></li><li><a …
=> fix(docker-tutorial): broken image and alt text

packages/projects-docs/pages/learn/integrations/github-app.mdx
It looks like URLs with a `#` are not rewritten correctly. Quickly fixing this with this change, we should take a look at this.
=> fix: make link with hashtag absolute

packages/projects-docs/pages/learn/integrations/github-app.mdx
The last change actually made it prepend the URL? Very confusing.
=> fix: put relative url back

packages/projects-docs/pages/faq.md, packages/projects-docs/pages/learn/introduction/workspace.md, packages/projects-docs/pages/learn/repositories/editors.md, packages/projects-docs/pages/learn/sandboxes/tests.md
Some links were resulting in 404 pages:
=> fix: update broken relative links

README.md, packages/projects-docs/pages/faq.md, packages/projects-docs/pages/learn/getting-started/your-first-repository.md, packages/projects-docs/pages/learn/integrations/github-app.mdx, packages/projects-docs/pages/learn/introduction/overview.md, packages/projects-docs/pages/learn/repositories/commandpalette.md, packages/projects-docs/pages/learn/repositories/devtools.md, packages/projects-docs/pages/learn/repositories/editors.md, packages/projects-docs/pages/learn/repositories/env.md, packages/projects-docs/pages/learn/repositories/interactive-readme.md, packages/projects-docs/pages/learn/repositories/limitations.md, packages/projects-docs/pages/learn/repositories/overview.md, packages/projects-docs/pages/learn/repositories/preview.md, packages/projects-docs/pages/learn/repositories/secrets.md, packages/projects-docs/pages/learn/repositories/task.md, packages/projects-docs/pages/learn/repositories/tasks.md, packages/projects-docs/pages/learn/repositories/terminal.md, packages/projects-docs/pages/learn/sandboxes/editors.md, packages/projects-docs/pages/learn/teams/team-overview.md, packages/projects-docs/pages/tutorial/cli-tool.md, packages/projects-docs/pages/tutorial/getting-started-with-docker.md, packages/projects-docs/pages/tutorial/install-system-packages.md
These updates are split into four main parts:
1. Update "CodeSandox Projects" and "Projects" mentions to "CodeSandox Repositories" and "Repositories", respectively.
2. Update "VSCode" to "VS Code".
3. Update "Github" to "GitHub".
4. Fix some typos and restructure some sentences for improved readability across several pages.
Note that the "Workspace" page is not up to date in this PR, considering the recent [PR](https://github.com/codesandbox/docs/pull/89) from @necoline.
=> Several copy updates

packages/projects-docs/pages/learn/introduction/overview.md, packages/projects-docs/pages/learn/repositories/editors.md, packages/projects-docs/pages/learn/sandboxes/editors.md, packages/projects-docs/pages/learn/sandboxes/overview.md
This PR updates existing pages to make it clear that Cloud Sandboxes now have VS Code support. It also fixes some typos and two broken links.
=> Add info about VS Code support for Cloud Sandboxes

packages/codesandbox-theme-docs/dist/index.js, packages/codesandbox-theme-docs/shared.config.js, packages/codesandbox-theme-docs/src/constants.tsx, packages/codesandbox-theme-docs/src/utils/get-git-edit-url.ts, packages/projects-docs/theme.config.js
Right now, when we share links to the docs, the generated previews mention Nextra instead of CodeSandbox:
After this gets merged, it will show the same content as when we share the website:
**Title**: CodeSandbox: Online Code Editor and IDE for Rapid Web Development
**Description**: CodeSandbox is an online code editor and prototyping tool that makes creating and sharing web apps faster
cc @filipelima18 if we want to change the content.
The Twitter user was also pointing to the library's creator instead of @codesandbox.
It currently builds a wrong URL leading to a broken experience when users try to edit the documentation by opening it in CodeSandbox.
**Current**:
https://user-images.githubusercontent.com/24959348/205129468-d70f82bf-414d-4e23-b662-9f39303bc4a2.mov
**Fixed**: …
=> fix(docs): meta tags + edit link

packages/projects-docs/pages/learn/repositories/env.md
Closes XTE-227
We do not want to encourage people to work with node_modules directly at this point, and also do not want to provide ways to overgoe this. So a quick update in the documentation should clear that up.
=> Extended explanation around node_modules visibility

packages/projects-docs/pages/learn/environment/vm.md, packages/projects-docs/pages/learn/introduction/workspace.md, packages/projects-docs/pages/learn/teams/permissions.md
This PR fixes some internal broken links in three Docs pages:
* [VM Config & Persistence](https://codesandbox.io/docs/learn/environment/vm)
* [Workspace](https://codesandbox.io/docs/learn/introduction/workspace)
* [User Permissions](https://codesandbox.io/docs/learn/teams/permissions)
I couldn't properly test this in the CodeSandbox preview (the Docs theme build failed), so I appreciate a review to double-check if the updated links are working as expected.
=> fix(docs): update internal broken links

.codesandbox/tasks.json, package.json, packages/codesandbox-theme-docs/README.md, packages/codesandbox-theme-docs/package.json, packages/projects-docs/README.md
The project isn't running in https://codesandbox.io/p/github/codesandbox/docs/main?file=%2Fpackage.json due to the build theme failing:
This PR fixes the build scripts.
It also updates the readme for the theme and the project packages since they were referencing Nextra and SWR instead of CodeSandbox.
=> chore: fix build and update readme

packages/projects-docs/pages/learn/environment/vm.md
We recently added the ability on the pitcher to configure a VM's node version using `engines` filed in package.json. This is a npm standard field which is used to define the least version of node that a project needs. 
Till now, users can change a node version only through `environment.json` or `.nvmrc` files. If a project is already using a using `engines` filed in package.json they still need to create one of those files.  This latest change fixes it.
Here is the priority order for the detection
`.nvmrc` > `environment.json` > `package.json`
=> Update support for engines variable in package.json for node version detection.

packages/projects-docs/pages/learn/environment/vm.md
when we say "we have defined these resources as default" are we talking about the baseline for pro?
Because the resources outlined in the docs don't align with free or pro specs, I changed it to match our pro specs since it was just one number off and I assume that is when we say we gauged for "usual resource needs" we had pro in mind, but since we don't mention pricing tiers here, I wasn't sure.
context: I came to update the specs after we changed the default [disk for free](https://linear.app/codesandbox/issue/XTD-593/update-pricing-info-to-reflect-new-disk-limits), but I don't know if we wanted to list free or pro specs here
=> Update VM specs in docs

packages/projects-docs/pages/learn/repositories/shortcuts.md
This simple PR updates the Keyboard Shortcuts page to reflect the new "Toggle Sidekick" shortcut. `⌘ .` now seems to trigger code actions instead.
=> fix(docs): Update sidekick shortcut

packages/projects-docs/pages/learn/environment/vm.md
This PR fulfills two main purposes:
1. Add a brief intro about what microVMs are and where we use them on the Environment page.
2. Explain that each branch and cloud sandbox gets a microVM and the specs are set to each one.
This came up during a user interview.
I also took the opportunity to tweak some wording.
=> docs(Environment): add details about microVMs + how we allocate resources

packages/projects-docs/pages/tutorial/_meta.json
I recently merged PR #130 but forgot to update the meta file that contains navigation. This PR fixes that.
=> fix(Docs): fix tutorial nav with Python link

packages/projects-docs/next.config.js
Recently, there was a major update to the [Repository Setup + Tips & Tricks](https://codesandbox.io/docs/learn/getting-started/setting-up-repository) page. The URL also changed but a redirect was not added.
This PR adds that missing redirect.
=> fix(Docs): add a new redirect to the Repository Setup page

packages/projects-docs/pages/learn/getting-started/setting-up-repository.mdx, packages/projects-docs/pages/learn/integrations/tailscale.mdx, packages/projects-docs/pages/learn/repositories/task.mdx, packages/projects-docs/pages/learn/repositories/tasks.mdx
- Follow-up to https://github.com/codesandbox/codesandbox-applications/pull/2580
- Related to ECO-321
Adds the `$schema` property into every `tasks.json` so our users would get auto-completion and validation of their `tasks.json` configurations. 
More motivation in [Linear](https://linear.app/codesandbox/issue/ECO-321/write-a-json-schema-for-tasksjson).
=> feat: add "$schema" reference to all "tasks.json"

packages/projects-docs/pages/learn/sandboxes/ci.mdx
We don't support Cloud Sandboxes in the CI yet. This adds a small note to the docs mentioning it.
Closes SPT-245.
=> fix: small note on CodeSandbox CI support for cloud sandboxes

packages/projects-docs/pages/learn/getting-started/setting-up-repository.mdx
This PR adds a new section to the Repository Setup + Tips & Tricks page on the Docs to highlight how the branching workflow works—namely, to emphasize how we do seamless branching.
I also took the opportunity to do a grammar review of the whole page.
Closes CP-811
=> docs(Repositories): Add Branching Workflow section and fix grammar

packages/projects-docs/pages/faq.mdx
This PR introduces some needed clarity updates on the FAQ, namely in adding some additional distinction between browser sandboxes and cloud sandboxes.
It also introduces a new FAQ item under "VS Code" explaining how to configure Copilot to work alongside CodeSandbox.
Finally, I took the time to do some grammar improvements.
=> docs(FAQ): update FAQs and add new item about Copilot

packages/projects-docs/pages/learn/getting-started/your-first-sandbox.mdx, packages/projects-docs/pages/learn/sandboxes/_meta.json, packages/projects-docs/pages/learn/sandboxes/cli-api.mdx, packages/projects-docs/pages/learn/sandboxes/overview.mdx, packages/projects-docs/pages/learn/sandboxes/synced-templates.mdx, packages/projects-docs/pages/learn/sandboxes/templates.mdx
This is a pretty big docs change. We introduce a new item for "Synced Templates" (templates created from GitHub) and add a new dedicated section for the CodeSandbox CLI and API, as they were not very discoverable (even not through search, for some reason), also the google results for CodeSandbox API are not there anymore. They need their own page.
=> feat: synced template documentation & cli/api changes

packages/projects-docs/pages/learn/sandboxes/overview.mdx
This PR updates the "Overview" page under "Sandboxes" to focus on Cloud Sandboxes by default.
It also adds a callout to highlight we recommend using cloud sandboxes in most cases.
=> docs(sandboxes): prioritize information on cloud sandboxes

packages/projects-docs/pages/learn/sandboxes/custom-npm-registry.mdx
the workaround with using `file` has a leading slash, but that's not needed
=> docs(npm): fix typo in "custom registry" page

packages/projects-docs/pages/learn/sandboxes/_meta.json
This PR fixes two broken navigation links under "Sandboxes".
- [Configuration](https://codesandbox.io/docs/learn/environment/secrets) is pointing to Secrets, so it seems like a duplicate.
- Deployment Options seems to be an empty reference.
=> fix(Sandboxes): remove broken navigation references

packages/projects-docs/next.config.js, packages/projects-docs/pages/learn/guides/_meta.json, packages/projects-docs/pages/learn/repositories/_meta.json
Added redirects for missing repo content that is available under devboxes. Fixes the menu that points to 404.
=> fix: Added redirects for missing repo content

packages/projects-docs/pages/learn/devboxes/synced-templates.mdx, packages/projects-docs/pages/learn/environment/vm.mdx, packages/projects-docs/pages/tutorial/getting-started-with-docker.mdx
Added instructions for creating a devcontainer configuration file and updated references to Dockerfile
=> fix: replace Dockerfile with devcontainer

README.md
I noticed this line "The Projects is leveraging [Nextra](https://nextra.vercel.app/), ...", I assumed it would be `Project` instead of `Projects`. I could be well wrong, but still drafted a PR for this. Please feel free to ignore/close the PR if it seems irrelevant. :smile:
=> Docs: small typo fix in README.md

packages/projects-docs/pages/learn/plans/usage-based-billing.mdx
Previous UBB redirect was to plans/plans from a previous naming convention
Updating to plans/subscriptions
=> style: Update link in usage-based billing page

packages/projects-docs/pages/learn/plans/_meta.json, packages/projects-docs/pages/learn/plans/codesandbox-friends.mdx, packages/projects-docs/pages/learn/plans/education-plans.mdx
Add new page with education plans and link it from the CSB Friends page.
=> chore: Add page with education plans

packages/projects-docs/pages/faq.mdx, packages/projects-docs/pages/learn/devboxes/devtools.mdx, packages/projects-docs/pages/learn/environment/vm.mdx, packages/projects-docs/pages/learn/integrations/tailscale.mdx, packages/projects-docs/pages/learn/sandboxes/custom-npm-registry.mdx
Updated support links to use support form instead of email in various pages
=> fix: Updating docs to point to new support form 

packages/projects-docs/pages/learn/repositories/getting-started/git-workflow.mdx
Add information on using terminal with Git on CodeSandbox for branch navigation and updating
=> feat: Add documentation on `checkout`

packages/projects-docs/pages/learn/ai/faqs.mdx, packages/projects-docs/pages/learn/plans/pricing-faq.mdx, packages/projects-docs/pages/learn/plans/subscriptions.mdx, packages/projects-docs/pages/learn/repositories/_meta.json, packages/projects-docs/pages/learn/sandboxes/custom-npm-registry.mdx, packages/projects-docs/pages/learn/sandboxes/faq.mdx
Summary:
- Fixed 7 broken links under Repositories navigation in the sidebar.
- Updated references to features and limits that have been changed in the latest pricing changes.
=> chore: update broken nav links and outdated content

packages/projects-docs/pages/learn/environment/vm.mdx
Preview [here](https://8nl543-3000.csb.app/learn/environment/vm). Needs a review of the technical accuracy of the changes, as I picked them up from a Slack thread.
=> chore: update information about VM persistence

packages/projects-docs/pages/faq.mdx
This PR removes an FAQ item that was deprecated by a recent pricing change.
=> chore: update outdated FAQ

packages/projects-docs/pages/faq.mdx, packages/projects-docs/pages/learn/repositories/collaborate-share.mdx, packages/projects-docs/pages/learn/repositories/getting-started/configure-vscode.mdx
- updates the FAQ on the status of iOS
- removes a few references to iOS left over in the docs
=> remove ios in docs

packages/projects-docs/pages/learn/_meta.json, packages/projects-docs/pages/learn/explore.mdx
The page was quite outdated and included references to Curators, which AFAIK are no longer active. This updated version points to the right URL and explains how the page gets populated with content.
Preview [here](https://pkvkvr-3000.csb.app/learn/explore).
=> fix: update broken link and outdated content in Explore page

packages/projects-docs/pages/learn/plans/codesandbox-friends.mdx
The old URL was leading to a broken Typeform.
=> chore: fix URL of CSB friends form

packages/projects-docs/pages/faq.mdx, packages/projects-docs/pages/learn/ai/codeium.mdx, packages/projects-docs/pages/learn/devboxes/preview.mdx, packages/projects-docs/pages/learn/integrations/tailscale.mdx, packages/projects-docs/pages/learn/plans/education-plans.mdx
Updated a lot of FAQ items that have been outdated for a while (mostly since we made VS Code Web our default editor and deprecated legacy Sandboxes).
Also added a few new FAQs from common user questions.
=> chore: update outdated Docs items and add new FAQs

packages/projects-docs/pages/sdk/faq.mdx
- Fixing unfinished sentence in VM spec selection question
- Adding clarification about confirmation prompt in previews
- Separating out SOC2 certification into own FAQ item
=> Improvements to SDK FAQs

packages/projects-docs/pages/sdk/use-cases.mdx
When reading the docs I ran into a 404. This fix points to a working page.
=> fix: update link to point to new together docs page

packages/projects-docs/pages/sdk/_meta.json, packages/projects-docs/pages/sdk/cli.mdx, pnpm-lock.yaml
Added docs for the CLI reference. The page can be previewed on: https://msh43r-3000.csb.app/sdk/cli. Screenshot of the page shown below.
=> feat(CLI): initial documentation for CLI

packages/projects-docs/pages/sdk/_meta.json
Removed playground section from _meta.json as it is a bad showcase and will shortly be replaced by a link to an implementation using the SDK instead
=> Remove playground entry from SDK metadata
